
GET http://localhost:4004/odata/v4/catalog/Employees

###


POST http://localhost:4004/odata/v4/catalog/Employees
Content-Type: application/json


{  
    "empId":1,
    "firstName":"Shubham",
    "lastName":"kumar",
    "mobileNumber":"7985919618",
    "address":"Marathalli",
    "city":"Bangalore",
    "state":"Karnataka",
    "pincode":"560036"
}

###

PATCH  http://localhost:4004/odata/v4/catalog/Employees/1
Content-Type: application/json


{
 
    "status":"Pending",
    "position":null,
    "email":null,
    "hrStatus":"Pending"

}

###

DELETE http://localhost:4004/odata/v4/catalog/Employees/2
Content-Type: application/json

###

